[project]
name = "3dgs-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ahrism10M501", email = "ariofeem@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "torch>=2.13.0",
    "torchvision>=0.28.0",
    "tqdm>=4.70.0",
]

[tool.uv]
package = false
